### PR TITLE
Made service + directive minification-safe

### PR DESCRIPTION
**Pull request by PangolinTO**
Lack of Dependency Injection was causing issues when using minification tools. Made the Directive and Service minification-safe so as to prevent further DI issues.

### CODE REVIEW

**Comment by quedicesebas** [comment]
@PangolinTO please modify the source files (src folder) not the dist files, dist files are generated

**Comment by PangolinTO** [comment]
Modified `src` files as well.

**Comment by quedicesebas** [comment]
Please check current code

**Comment by PangolinTO** [comment]
Solved merge conflicts.

**Comment by quedicesebas** [comment]
I think current code already resolve your issue

**Pull request closed without merging**
